addr: 0.0.0.0:8080
log_file: logs/audit.jsonl
profiles:
  - generic
  - openai
allow_hosts:
  - "*"
excerpt_limit: 2048
mitm: true
mitm_ca: certs/ca.pem
mitm_key: certs/ca.key
mitm_disable_hosts:
  - api.openai.com
filters:
  allowlist:
    type: header-block
    header: X-Audit-Block
profiles_config:
  openai:
    redact_system_prompt: true
